### ISSUE TITLE
Does this Orb require any changes to work with DockerHub auth?

### ISSUE THREAD

**Issue by wheresrhys** [CircleCI-Public/heroku-orb#19]
## Describe Request:
When DockerHub starts rate limiting anonymous requests on Nov 1st, it looks like this Orb will be impacted, since there's no auth key in the docker config. It looks like a standard pattern is to expect DOCKERHUB_USERNAME/DOCKERHUB_PASSWORD environment variables (see example), will this (or something equivalent) be required for this Orb?

## Examples:
https://discuss.circleci.com/t/updated-authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567/35

**Comment by gmemstr** [comment]
CircleCI has partnered with Docker Hub and will not be subject to rate limiting - you can read more here: support.circleci.com/hc/en-us/articles/360050623311-Docker-Hub-rate-limiting-FAQ
