### ISSUE TITLE
Heroku Orb environment spin up error

### ISSUE THREAD

**Issue by ignaciojcano** [CircleCI-Public/heroku-orb#3]
Brought over from: https://github.com/CircleCI-Public/circleci-orbs/issues/281 after I realized it was moved to this new repo
### Orb version

heroku@1.0.0

### What happened

I kept getting an error when trying to do the deployment During the "Spin up Environment"
```sh
Build-agent version 1.0.26573-ff13bd88 (2020-01-30T20:25:39+0000)
Docker Engine Version: 18.09.6
Kernel Version: Linux d9e1f5589e45 4.15.0-1052-aws #54-Ubuntu SMP Tue Oct 1 15:43:26 UTC 2019 x86_64 Linux
Starting container cimg:base/stable
  image cache not found on this host, downloading cimg:base/stable

invalid reference format
```

### Expected behavior

Ideally it should spin up the environment, I was able to get past this by manually setting the executor to be:
```
docker:
      - image: buildpack-deps:bionic
```
instead of
```
executor: heroku/default
```

It seems as if it is wrongly setting the base container to `cimg:base/stable` when it should be `cimg/base:stable`

**Comment by golmansax** [comment]
Any updates here?  It'd be great to fix this error because the documentation for the Heroku orb (https://circleci.com/orbs/registry/orb/circleci/heroku) does not work out of the box.

**Comment by lokst** [comment]
@ignaciojcano @golmansax Thank you for reporting the error! A fix for this is in progress.

**Comment by lokst** [comment]
`circleci/heroku@1.0.1` which fixes the issue has been released 🎉

**Comment by golmansax** [comment]
@lokst Thanks!  The fix worked.
