### ISSUE TITLE
Wanting to use the review app feature, latest version pushed to circle orbs doesn't include

### ISSUE THREAD

**Issue by cbarratt** [CircleCI-Public/heroku-orb#38]
Hey!

I was wondering if at any point we might see a push to the circleci orbs registry in the near future?

Thanks

**Comment by matheusbras** [comment]
Please push it to the registry. 🙏🏼

**Comment by tomasmuller** [comment]
@cbarratt [Following the project README](https://github.com/CircleCI-Public/heroku-orb#how-to-contribute), it should be live in the registry. Something went wrong in the [last integration](https://github.com/CircleCI-Public/heroku-orb/commits/master). It looks like we should remove the `integration-test-review` job from the Circle CI config.

<img width="865" alt="Screen Shot 2022-04-25 at 3 28 54 PM" src="https://user-images.githubusercontent.com/181868/165151454-595e955a-baa5-47dd-bc46-7bc9c36a4818.png">

See: https://app.circleci.com/pipelines/github/CircleCI-Public/heroku-orb/123/workflows/6fef177e-4db3-4b17-ba47-aa9ffb144183/jobs/340

**Comment by matheusbras** [comment]
@KyleTryon can you help us here, please? 🙏🏼

**Comment by KyleTryon** [comment]
Hello, Version 2.0.0 of the Heroku orb has just been published. Please let us know if you experience any issues.

https://circleci.com/developer/orbs/orb/circleci/heroku
