### ISSUE TITLE
Deploy via git timing out even though deploy succeeds

### ISSUE THREAD

**Issue by zetter** [CircleCI-Public/heroku-orb#39]
**Orb Version**
1.2.6

**Describe the bug**

We're seeing the `deploy-via-git` command provided by this orb sometimes fail because of a timeout even though the deploy has already succeeded.

We see the deploy appear successfully in Heroku before the timeout completes. 

For example, for one build `deploy-via-git` command ran from `11:52:33 UTC` to `12:10:22 UTC`
From the Heroku console I can see the deploy completed successfully at `12:00:21 UTC` - 10 minutes before the timeout.

Example output from a failed build:

```
[SNIP]
remote: -----> Discovering process types        
remote:        Procfile declares types -> [SNIP]
remote: 
remote: -----> Compressing...        
remote:        Done: [SNIP]        
remote: -----> Launching...        
remote:  !     Release command declared: this new release will not be available until the command succeeds.        
remote:        Released [SNIP]        
remote:        [SNIP] deployed to Heroku        
remote: 
remote: This app is using the Heroku-18 stack, which is supported until April 30th, 2023.        
remote: A newer stack is available: Heroku-20. To upgrade, see:        
remote: https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack        
remote: 

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**To Reproduce**

This is intermittent, we noticed in in 3 out of our 4 deploys this morning. 

**Expected behavior**

The orb command completes successfully

**Additional context** 

I'm not sure if this problem is due to a problem with the Orb or Heroku. 
I've not seen any issue on Heroku's status page, and the build is reported as succeeded on Heroku's console which makes me think it's the Orb. I'd be interested in hearing from anyone else who has seen this issue (with our without using the Heroku Orb)

**Comment by KyleTryon** [comment]
Hello, Version 2.0.0 of the Heroku orb has just been published. Please let us know if you experience any issues.

https://circleci.com/developer/orbs/orb/circleci/heroku
