### ISSUE TITLE
Heroku CLI v10 breaking `Heroku container:release` command

### ISSUE THREAD

**Issue by aaronmiler** [CircleCI-Public/heroku-orb#56]
**Orb Version**
Initially observed in 1.2.6, also fails on 2.0.0

**Describe the bug**
The following command (`heroku container:release -a << parameters.heroku_app_name >> web worker release`) seems to work on Heroku, but the verification from the orb (for success/failure) seems to fail.

Last successful deploy using this command, was 3 days ago (pre-Heroku version release), using the version 9.5.x Heroku CLI

**To Reproduce**

Ensure that version 10 of the Heroku CLI is installed
Runn a `heroku container:release` command once the images are pushed and available

Produced Error
```
Releasing images web,worker,release to ccpayments-staging... done
Running release command...
    TypeError: Cannot read properties of undefined (reading 'statusCode')

Exited with code exit status 1
```

**Comment by marboledacci** [comment]
Do you know if that command is working outside of CircleCI using the version 10?

**Comment by aaronmiler** [comment]
Good callout @marboledacci, appears the issue has also been reported on the [Heroku CLI](https://github.com/heroku/cli/issues/3142).

Closing the issue now that we can watch it there.
